name: Deploy Next.js to Hostinger

on:
  push:
    branches:
      - main # ඔයාගේ බ්‍රාන්ච් එක master නම් master කියලා දාන්න

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # <--- මෙතන 22 කියලා මාරු කරන්න

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: 🚀 Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: ./public_html/